# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
require 'support/vcr_setup'
require 'webmock/rspec'

module CarmaLinkSDK
  Spec = {}
end

require 'rspec'
require 'carmalinksdk'
require 'support/config'

def reload_config_class
     # this is a hacky workaround for now, but we need to reload the Config classes for other tests
    Object::CarmaLinkSDK.send(:remove_const, 'BaseConfig')
    Object::CarmaLinkSDK.send(:remove_const, 'GeneralConfig')
    Object::CarmaLinkSDK.send(:remove_const, 'Config')
    load 'carmalinksdk/config.rb'
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  
  config.include WebMock::API 

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

